Use MMN url from config
mysteriumnetwork/dvpn-web pull request #134
Opened 2020-10-06 14:30 UTC by mdomasevicius

2020-10-06 14:33 UTC, ignasbernotas approved these changes

2020-10-06 14:36 UTC, Waldz requested changes

2020-10-06 14:36 UTC, Waldz commented on src/Pages/AppRouter.tsx
> +    config: state.app.config,
Suggest to move `config` fetching from Dashboard to some upper layer, as it's needed for other pages

2020-10-07 10:10 UTC, Waldz approved these changes

2020-10-07 10:11 UTC, merged