Node UI should show bounty widget
mysteriumnetwork/dvpn-web pull request #150
Opened 2020-12-03 12:00 UTC by Waldz

Closes: https://github.com/mysteriumnetwork/node/issues/2877

2020-12-03 16:07 UTC, mdomasevicius approved these changes

2020-12-04 05:45 UTC, chompomonim requested changes

2020-12-04 05:45 UTC, chompomonim commented on src/Pages/Authenticated/Dashboard/Bounty/BountyWidget.tsx
> +                    <span className="bounty__body__label">out of 8</span>
Why "out of 8"? Because of our bounty rules it should be "out of 3".

2020-12-04 05:45 UTC, chompomonim commented on src/Pages/Authenticated/Dashboard/Bounty/BountyWidget.tsx
> +                    <div>Eligible</div>
Not every node is eligible for residential bounty. This should be a parameter.

2020-12-08 19:35 UTC, ignasbernotas approved these changes

2020-12-08 20:10 UTC, mdomasevicius approved these changes

2020-12-08 23:53 UTC, chompomonim approved these changes

2020-12-09 07:01 UTC, merged