Notification for node version update
mysteriumnetwork/dvpn-web pull request #346
Opened 2022-08-05 10:07 UTC by MykolasMaciekus

- API call to check current release version in GitHub
- Refactored notification display logic
- Required styling for update notification
- Remote storage utilization to check last check time to avoid calling api.github.com on every rerender

2022-08-05 10:49 UTC, mdomasevicius requested changes

2022-08-05 10:49 UTC, mdomasevicius commented on src/api/node-version.management.ts
> +export const checkNodeVersion = async () => {
You are not checking node version in `checkNodeVersion` you are fetching latest node version.

2022-08-05 10:49 UTC, mdomasevicius commented on src/api/node-version.management.ts
> +    return err
Let's not have double return types. Typically if you want to pass down errors you should put re-throw them down the stack by: `throw err`

2022-08-05 10:49 UTC, mdomasevicius commented on src/Pages/Authenticated/Components/Notifications/Notifications.tsx
> +        if (!lastCheck || now > lastCheck + 7200000) {
in the case that humans are terrible at translating milliseconds I'd say move this magic number to constant like `const TWO_HOURS_MS = 2 * 60 * 60 * 1000`

2022-08-05 10:49 UTC, mdomasevicius commented on src/theme/light.ts
> +        background: themeCommon.colorYellow + alphaToHex(0.1),
I wonder if we could use this so we could just write something like

```
background: themeCommon.colorYellow + 0.1.hex(),
```

2022-08-05 10:49 UTC, mdomasevicius commented on src/Pages/Authenticated/Components/Notifications/List.tsx
> +          variant={notification.variant as CardVariant}
`as` cast seems not necessary

2022-08-05 12:17 UTC, MykolasMaciekus commented on src/theme/light.ts
> +        background: themeCommon.colorYellow + alphaToHex(0.1),
Looks a lot like python to me, have you considered how can we implement this?

2022-08-08 06:04 UTC, mdomasevicius approved these changes

2022-08-08 06:08 UTC, merged